2019-10-08 14:05:20,995 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 14:05:38,390 ERROR: Exception on /edit_profile [POST] [in /scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py:1891]
Traceback (most recent call last):
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlite3.IntegrityError: UNIQUE constraint failed: user.username

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/scratch/knerr/repos/mydrop/mytrilog/app/routes.py", line 100, in edit_profile
    db.session.commit()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/orm/scoping.py", line 162, in do
    return getattr(self.registry(), name)(*args, **kwargs)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 1027, in commit
    self.transaction.commit()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 494, in commit
    self._prepare_impl()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 473, in _prepare_impl
    self.session.flush()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2459, in flush
    self._flush(objects)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2597, in _flush
    transaction.rollback(_capture_exception=True)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/util/langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 153, in reraise
    raise value
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/orm/session.py", line 2557, in _flush
    flush_context.execute()
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 422, in execute
    rec.execute(self)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/orm/unitofwork.py", line 589, in execute
    uow,
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 236, in save_obj
    update,
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/orm/persistence.py", line 996, in _emit_update_statements
    statement, multiparams
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 988, in execute
    return meth(self, multiparams, params)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/sql/elements.py", line 287, in _execute_on_connection
    return connection._execute_clauseelement(self, multiparams, params)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1107, in _execute_clauseelement
    distilled_params,
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1253, in _execute_context
    e, statement, parameters, cursor, context
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1473, in _handle_dbapi_exception
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/util/compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1249, in _execute_context
    cursor, statement, parameters, context
  File "/scratch/knerr/venvs/mytrilog/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 552, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.IntegrityError: (sqlite3.IntegrityError) UNIQUE constraint failed: user.username
[SQL: UPDATE user SET username=?, about_me=? WHERE user.id = ?]
[parameters: ('susan', 'author of this app', 1)]
(Background on this error at: http://sqlalche.me/e/gkpj)
2019-10-08 14:22:14,516 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 14:22:33,181 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 14:22:59,485 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 14:23:36,475 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 14:27:02,957 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 14:37:26,183 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 14:37:32,903 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 14:46:26,499 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 14:46:32,504 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 14:59:13,951 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 15:01:21,409 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 15:04:24,823 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 15:05:26,625 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 15:06:48,396 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 15:08:55,272 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 15:09:39,016 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 15:09:43,156 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 15:09:47,569 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-08 15:18:21,157 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-09 14:19:18,314 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-09 15:20:32,998 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
2019-10-09 15:21:31,453 INFO: MyTriLog startup... [in /scratch/knerr/repos/mydrop/mytrilog/app/__init__.py:43]
